### ISSUE TITLE
相同的页面跳转无动画。且页面缓存信息有误

### ISSUE THREAD

**Issue by wenjianli92** [hezhongfeng/vue-page-stack-example#15]

**Comment by wenjianli92** [comment]
你下图示例中的“push到下一页怎么实现的”
![image](https://user-images.githubusercontent.com/29296692/93854842-0c2bd480-fce9-11ea-993c-8c6f95df258e.png)

**Comment by wenjianli92** [comment]
A也买跳转A页面，当前页码有增加，但是页面没触发动效

**Comment by wenjianli92** [comment]
> 这个demo.A页面跳A页面有问题
> ![image](https://user-images.githubusercontent.com/29296692/93854717-d4249180-fce8-11ea-9e2c-a7a8a97b6a76.png)

**Comment by hezhongfeng** [comment]
我刚看了，这个项目没这个问题，可以对比这个项目的源码
