### ISSUE TITLE
开发环境下 修改代码后 热更新刷新 页面显示空白

### ISSUE THREAD

**Issue by hu19940121** [hezhongfeng/vue-page-stack-example#18]
开发环境下 修改代码后 热更新自动刷新后 页面会显示空白  手动刷新一下浏览器就好了  。 希望作者修复这个问题

**Comment by hezhongfeng** [comment]
因为我们的缓存的vnode在热更新时候无法一起更新
暂时无解~准备等Vue3稳定了升级一波
