### ISSUE TITLE
想请教下：底部导航的页面，切换页面时，tab上的也页面是路由切换还是写成组件再一个页面中显示隐藏

### ISSUE THREAD

**Issue by Akira0705** [hezhongfeng/vue-page-stack-example#34]
![image](https://user-images.githubusercontent.com/28581396/149742195-311314b5-0e7c-48aa-b847-be8a1162bb38.png)

像这种底部导航的页面，我现在是 一个 dashboard.vue 的页面 下有两个子路由 比如：home.vue , about.vue。切换的时候会路由跳转的。
但是像您示例中的是显示隐藏，示例也已经很久之前的了，所以想请教一下：
能像原生APP一样开发的方式，这种底部导航页应该：
1、嵌套子路由，路由跳转
2、一个组件内显示、隐藏
3、或是 如今您能想到更好的方案

望能交流一下

**Comment by hezhongfeng** [comment]
我觉得应该【一个组件内显示、隐藏】
因为一般这种情况，是常驻的首页，你玩玩微信支付宝就能发现，在第一个tab上的操作或者输入，在你操作完其他的Tab后是肯定会给你保留状态的。
