### ISSUE TITLE
clone代码后报错

### ISSUE THREAD

**Issue by saikete** [hezhongfeng/vue-page-stack-example#49]
clone===> yarn 后 报error错

**Comment by saikete** [comment]
是node版本和yarn版本，运行成功版本：node：v14.20.1,yarn版本：v1.22.19

**Comment by hezhongfeng** [comment]
好的，这个是几年前的环境了，自己切换下~

**Comment by saikete** [comment]
没有计划适配一下v3吗

**Comment by hezhongfeng** [comment]
不是我不做~目前做不到~

**Comment by saikete** [comment]
哈哈哈哈我刚刚看了下Vue3目前没法像v2一样直接写实例上的keepAlive属性是吗
