### ISSUE TITLE
浏览器刷新后，返回上一页报错

### ISSUE THREAD

**Issue by liuchengbin8** [hezhongfeng/vue-page-stack-example#53]
![vue-page-stack](https://github.com/hezhongfeng/vue-page-stack-example/assets/13991183/d45e4a6d-9ea7-4659-9782-30503fce1845)

**Comment by hezhongfeng** [comment]
刷新不行啊，刷新会丢失所有数据的

**Comment by liuchengbin8** [comment]
可以优化下吗？数据丢失没问题，但是浏览器前进后退可以正常操作

**Comment by hezhongfeng** [comment]
好的，我试试

**Comment by hezhongfeng** [comment]
@liuchengbin8  最新版 v3.1.1 解决了

**Comment by liuchengbin8** [comment]
> @liuchengbin8 最新版 v3.1.1 解决了

感谢大佬

**Comment by liuchengbin8** [comment]
> @liuchengbin8 最新版 v3.1.1 解决了

有个问题，浏览器刷新后，返回上一页，不会触发activated了吗

**Comment by hezhongfeng** [comment]
肯定没有了啊

**Comment by liuchengbin8** [comment]
> 肯定没有了啊
以前用2.0版本是还有的。
场景是这样的：页面A->B，页面A是在onActivated获取数据的，现在在页面B刷新后返回A，不会触发onActivated了

**Comment by hezhongfeng** [comment]
刷新了，什么都没了，肯定不会触发了啊
