### ISSUE TITLE
刷新浏览器，导致页面出错

### ISSUE THREAD

**Issue by liuchengbin8** [hezhongfeng/vue-page-stack-example#56]
页面A 跳转到-> 页面B，在页面B刷新浏览器。
点击返回A，再跳转到B，然后返回A，这时候页面A出错了，页面点击无反应。

**Comment by hezhongfeng** [comment]
给个最小的复现 repo 吧

**Comment by liuchengbin8** [comment]
现在这个example项目就能复现



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月12日(周五) 上午8:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hezhongfeng/vue-page-stack-example] 刷新浏览器，导致页面出错 (Issue #56)




 
给个最小的复现 repo 吧

**Comment by hezhongfeng** [comment]
好的，我找时间看看咋回事儿

**Comment by hezhongfeng** [comment]
@liuchengbin8 试试 v3.1.4

**Comment by liuchengbin8** [comment]
> @liuchengbin8 试试 v3.1.4

感谢，可以了
