### ISSUE TITLE
后退多级页面时，缓存失效

### ISSUE THREAD

**Issue by liuchengbin8** [hezhongfeng/vue-page-stack-example#57]
比如调用router.go(-2)返回上两级页面时，缓存会失效

**Comment by hezhongfeng** [comment]
有复现的最小 rep 吗？

**Comment by liuchengbin8** [comment]
> 有复现的最小 rep 吗？

当前这个example项目就能复现。
操作步骤：A -> B -> C，在页面C调用router.go(-2)，返回页面A，页面A缓存失效

**Comment by hezhongfeng** [comment]
好的，我看看

**Comment by hezhongfeng** [comment]
@liuchengbin8 新版本 v3.2.0 试试

**Comment by liuchengbin8** [comment]
感谢大佬，可以了

**Comment by hezhongfeng** [comment]
我目前已经很少做移动端了，所以平时都不用，也就很难发现一些问题～

**Comment by liuchengbin8** [comment]
理解，我也是最近做移动端比较多才会遇到
