### ISSUE TITLE
返回页面记住滚动的位置，安卓可以，ios不行

### ISSUE THREAD

**Issue by jinghaonode** [hezhongfeng/vue-page-stack-example#9]
期待作者完善

**Comment by jinghaonode** [comment]
另外，url中出现的stack-key能不能通过其他方式实现，放在url上不太美观

**Comment by hezhongfeng** [comment]
1、ios是可以的，参考https://github.com/hezhongfeng/vue-page-stack/issues/70
2、不行，这个是核心
